
FROM eclipse-temurin:21.0.8_9-jdk AS builder
WORKDIR /app
# teljes aktualis projekt masolasa a kontenerbe
COPY mvnw pom.xml ./
COPY .mvn .mvn
# futtatasi jog
RUN apt update && apt install -y dos2unix && \
    chmod +x mvnw && \
    dos2unix mvnw
RUN ./mvnw test
COPY src ./src
# futtatas
RUN ./mvnw package

FROM eclipse-temurin:21.0.8_9-jdk
WORKDIR /app
COPY --from=builder /app/target/*.jar employees.jar
CMD ["java", "-jar", "employees.jar"]