name: Build employees project
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Say Hello
              run: echo "Hello Github Actions!"