name: Build employees project
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                    distribution: 'temurin'
                    java-version: '21'
            - name: Build with Maven
              run: ./mvnw -B package