name: Build employees project
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'
            - name: Build with Maven
              run: ./mvnw -B package

            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                    name: employees-jar
                    path: target/employees-*.jar

    integration-tests:
        if: false # Set to true to enable integration tests
        runs-on: ubuntu-latest
        needs: build
        env:
            SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/employees
            SPRING_DATASOURCE_USERNAME: employees
            SPRING_DATASOURCE_PASSWORD: employees
        services:
            mariadb:
                image: mariadb:12.1.1-rc
                env:
                    MARIADB_DATABASE: employees
                    MARIADB_USER: employees
                    MARIADB_PASSWORD: employees
                    MARIADB_ROOT_PASSWORD: employees
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="healthcheck.sh --connect --innodb_initialized"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'

            - name: Build with Maven
              run: ./mvnw -B verify

    build-image:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Download Employee artifact
              uses: actions/download-artifact@v4
              with:
                  name: employees-jar
                  path: target/

            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                    context: .
                    file: Dockerfile.layers
                    push: true
                    tags: ghcr.io/${{ github.repository }}:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build-image

        steps:
            - run: echo "Deploy application here"